import { PrismaClient, Gender, UserStatus } from '@prisma/client';

const prisma = new PrismaClient();

const users = [
  {
    name: 'Aarav Sharma',
    email: 'aarav.sharma@gmail.com',
    primaryMobile: '+919876543210',
    secondaryMobile: '+919876543211',
    aadhaar: '234567890123',
    pan: 'ABCPS1234A',
    dateOfBirth: new Date('1995-03-15'),
    placeOfBirth: 'Mumbai, Maharashtra',
    currentAddress: '42, Bandra West, Carter Road, Mumbai, Maharashtra 400050',
    permanentAddress: '42, Bandra West, Carter Road, Mumbai, Maharashtra 400050',
    gender: Gender.MALE,
    status: UserStatus.ACTIVE,
    emailVerified: true,
    mobileVerified: true,
    createdBy: 'system-seed',
    updatedBy: 'system-seed',
  },
  {
    name: 'Priya Patel',
    email: 'priya.patel@outlook.com',
    primaryMobile: '+919123456789',
    aadhaar: '345678901234',
    pan: 'BCDPP5678B',
    dateOfBirth: new Date('1992-07-22'),
    placeOfBirth: 'Ahmedabad, Gujarat',
    currentAddress: '15, Satellite Road, Jodhpur Village, Ahmedabad, Gujarat 380015',
    permanentAddress: '88, Navrangpura, Ahmedabad, Gujarat 380009',
    gender: Gender.FEMALE,
    status: UserStatus.ACTIVE,
    emailVerified: true,
    mobileVerified: true,
    createdBy: 'system-seed',
    updatedBy: 'system-seed',
  },
  {
    name: 'Rohan Gupta',
    email: 'rohan.gupta@yahoo.com',
    primaryMobile: '+918765432109',
    secondaryMobile: '+918765432110',
    aadhaar: '456789012345',
    pan: 'CDEFG9012C',
    dateOfBirth: new Date('1988-11-30'),
    placeOfBirth: 'New Delhi',
    currentAddress: '301, DLF Phase 3, Sector 24, Gurugram, Haryana 122002',
    permanentAddress: '12, Lajpat Nagar, New Delhi 110024',
    gender: Gender.MALE,
    status: UserStatus.ACTIVE,
    emailVerified: false,
    mobileVerified: true,
    createdBy: 'system-seed',
    updatedBy: 'system-seed',
  },
  {
    name: 'Ananya Reddy',
    email: 'ananya.reddy@gmail.com',
    primaryMobile: '+917654321098',
    aadhaar: '567890123456',
    pan: 'DEFHR3456D',
    dateOfBirth: new Date('1998-01-10'),
    placeOfBirth: 'Hyderabad, Telangana',
    currentAddress: '7-1-397, Ameerpet, Hyderabad, Telangana 500016',
    permanentAddress: '7-1-397, Ameerpet, Hyderabad, Telangana 500016',
    gender: Gender.FEMALE,
    status: UserStatus.ACTIVE,
    emailVerified: true,
    mobileVerified: false,
    createdBy: 'system-seed',
    updatedBy: 'system-seed',
  },
  {
    name: 'Vikram Singh',
    email: 'vikram.singh@hotmail.com',
    primaryMobile: '+916543210987',
    aadhaar: '678901234567',
    pan: 'EFGVS7890E',
    dateOfBirth: new Date('1985-06-05'),
    placeOfBirth: 'Jaipur, Rajasthan',
    currentAddress: '23, C-Scheme, Ashok Nagar, Jaipur, Rajasthan 302001',
    permanentAddress: '45, Vaishali Nagar, Jaipur, Rajasthan 302021',
    gender: Gender.MALE,
    status: UserStatus.INACTIVE,
    emailVerified: false,
    mobileVerified: false,
    createdBy: 'system-seed',
    updatedBy: 'system-seed',
  },
  {
    name: 'Meera Krishnan',
    email: 'meera.krishnan@gmail.com',
    primaryMobile: '+915432109876',
    secondaryMobile: '+915432109877',
    aadhaar: '789012345678',
    pan: 'FGHMK1234F',
    dateOfBirth: new Date('1990-09-18'),
    placeOfBirth: 'Chennai, Tamil Nadu',
    currentAddress: '56, Anna Nagar East, Chennai, Tamil Nadu 600102',
    permanentAddress: '12, T Nagar, Chennai, Tamil Nadu 600017',
    gender: Gender.FEMALE,
    status: UserStatus.ACTIVE,
    emailVerified: true,
    mobileVerified: true,
    createdBy: 'system-seed',
    updatedBy: 'system-seed',
  },
  {
    name: 'Arjun Nair',
    email: 'arjun.nair@proton.me',
    primaryMobile: '+914321098765',
    aadhaar: '890123456789',
    pan: 'GHIAN5678G',
    dateOfBirth: new Date('1993-12-25'),
    placeOfBirth: 'Kochi, Kerala',
    currentAddress: '33, MG Road, Ernakulam, Kochi, Kerala 682011',
    permanentAddress: '33, MG Road, Ernakulam, Kochi, Kerala 682011',
    gender: Gender.MALE,
    status: UserStatus.ACTIVE,
    emailVerified: true,
    mobileVerified: true,
    createdBy: 'system-seed',
    updatedBy: 'system-seed',
  },
  {
    name: 'Kavya Iyer',
    email: 'kavya.iyer@gmail.com',
    primaryMobile: '+913210987654',
    aadhaar: '901234567890',
    pan: 'HIJKI9012H',
    dateOfBirth: new Date('1997-04-08'),
    placeOfBirth: 'Bangalore, Karnataka',
    currentAddress: '78, Indiranagar, 100 Feet Road, Bangalore, Karnataka 560038',
    permanentAddress: '22, Koramangala 4th Block, Bangalore, Karnataka 560034',
    gender: Gender.FEMALE,
    status: UserStatus.ACTIVE,
    emailVerified: false,
    mobileVerified: true,
    createdBy: 'system-seed',
    updatedBy: 'system-seed',
  },
  {
    name: 'Siddharth Malhotra',
    email: 'sid.malhotra@gmail.com',
    primaryMobile: '+912109876543',
    aadhaar: '012345678901',
    pan: 'IJKSM3456I',
    dateOfBirth: new Date('1991-08-14'),
    placeOfBirth: 'Chandigarh',
    currentAddress: '9, Sector 17, Chandigarh 160017',
    permanentAddress: '9, Sector 17, Chandigarh 160017',
    gender: Gender.MALE,
    status: UserStatus.INACTIVE,
    emailVerified: true,
    mobileVerified: false,
    createdBy: 'system-seed',
    updatedBy: 'system-seed',
  },
  {
    name: 'Diya Banerjee',
    email: 'diya.banerjee@outlook.com',
    primaryMobile: '+911098765432',
    secondaryMobile: '+911098765433',
    aadhaar: '123456789012',
    pan: 'JKLDB7890J',
    dateOfBirth: new Date('1994-02-28'),
    placeOfBirth: 'Kolkata, West Bengal',
    currentAddress: '101, Salt Lake, Sector V, Kolkata, West Bengal 700091',
    permanentAddress: '45, Park Street, Kolkata, West Bengal 700016',
    gender: Gender.FEMALE,
    status: UserStatus.ACTIVE,
    emailVerified: true,
    mobileVerified: true,
    createdBy: 'system-seed',
    updatedBy: 'system-seed',
  },
];

async function main() {
  console.log('🌱 Seeding database...');

  for (const user of users) {
    const created = await prisma.user.upsert({
      where: { email: user.email },
      update: {},
      create: user,
    });
    console.log(`  ✅ Created user: ${created.name} (${created.email})`);
  }

  console.log(`\n🎉 Seeded ${users.length} users successfully!`);
}

main()
  .catch((e) => {
    console.error('❌ Seed failed:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
