-- CreateTable
CREATE TABLE `users` (
    `id` VARCHAR(36) NOT NULL,
    `name` VARCHAR(100) NOT NULL,
    `email` VARCHAR(255) NOT NULL,
    `primaryMobile` VARCHAR(15) NOT NULL,
    `secondaryMobile` VARCHAR(15) NULL,
    `aadhaar` CHAR(12) NOT NULL,
    `pan` CHAR(10) NOT NULL,
    `dateOfBirth` DATE NOT NULL,
    `placeOfBirth` VARCHAR(255) NOT NULL,
    `currentAddress` TEXT NOT NULL,
    `permanentAddress` TEXT NOT NULL,
    `gender` ENUM('MALE', 'FEMALE', 'OTHER') NULL,
    `profilePhotoUrl` VARCHAR(500) NULL,
    `status` ENUM('ACTIVE', 'INACTIVE') NOT NULL DEFAULT 'ACTIVE',
    `emailVerified` BOOLEAN NOT NULL DEFAULT false,
    `mobileVerified` BOOLEAN NOT NULL DEFAULT false,
    `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updatedAt` DATETIME(3) NOT NULL,
    `deletedAt` DATETIME(3) NULL,
    `isDeleted` BOOLEAN NOT NULL DEFAULT false,
    `version` INTEGER NOT NULL DEFAULT 1,
    `createdBy` VARCHAR(100) NOT NULL,
    `updatedBy` VARCHAR(100) NOT NULL,

    UNIQUE INDEX `users_email_key`(`email`),
    UNIQUE INDEX `users_aadhaar_key`(`aadhaar`),
    UNIQUE INDEX `users_pan_key`(`pan`),
    INDEX `idx_name`(`name`),
    INDEX `idx_primaryMobile`(`primaryMobile`),
    INDEX `idx_isDeleted`(`isDeleted`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
